nameOverride: biomass-ingestion
fullnameOverride: biomass-ingestion

namespace: production

image:
  repository: "478544567935.dkr.ecr.us-east-1.amazonaws.com/bebeque/biomass-ingestion"
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  name: biomass-ingestion
  iamRoleArn: "arn:aws:iam::478544567935:role/bebeque-biomass-ingestion-role"  # fill in after terraform apply finishes

service:
  enabled: false

replicaCount: 0

hpa:
  enabled: false

keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 300
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/478544567935/bebeque-biomass-queue"
  sqsQueueLength: "5"
  awsRegion: us-east-1

env:
  APP_ENV: production
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/478544567935/bebeque-biomass-queue"
  SQS_WAIT_TIME_SECONDS: "20"
  SQS_VISIBILITY_TIMEOUT: "30"

probes:
  enabled: false

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

terminationGracePeriodSeconds: 30

networkPolicy:
  enabled: true