nameOverride: notification-service
fullnameOverride: notification-service

namespace: staging

image:
  repository: "478544567935.dkr.ecr.us-east-1.amazonaws.com/bebeque/notification-service"
  tag: "latest"
  pullPolicy: Always

serviceAccount:
  name: notification-service
  iamRoleArn: "arn:aws:iam::478544567935:role/bebeque-notification-service-role"  # fill in after terraform apply finishes

service:
  enabled: true
  port: 8000
  targetPort: 8000

replicaCount: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

keda:
  enabled: false

env:
  APP_ENV: staging
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/478544567935/bebeque-notifications-queue"
  SQS_WAIT_TIME_SECONDS: "20"

probes:
  enabled: true
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

terminationGracePeriodSeconds: 30

networkPolicy:
  enabled: true