name: Deploy analytics-api

on:
  push:
    branches:
      - main
    paths:
      - 'services/analytics-api/**'
      - 'helm/bebeque-service/**'
      - '.github/workflows/deploy-analytics-api.yml'
      - '.github/workflows/deploy-service.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: analytics-api
      helm-values-staging: helm/bebeque-service/values/analytics-api.staging.yaml
      helm-values-production: helm/bebeque-service/values/analytics-api.production.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}