name: Deploy biomass-ingestion

on:
  push:
    branches:
      - main
    paths:
      - 'services/biomass-ingestion/**'
      - 'helm/bebeque-service/**'
      - '.github/workflows/deploy-biomass-ingestion.yml'
      - '.github/workflows/deploy-service.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: biomass-ingestion
      helm-values-staging: helm/bebeque-service/values/biomass-ingestion.staging.yaml
      helm-values-production: helm/bebeque-service/values/biomass-ingestion.production.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}